name: Build and Validate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  actions: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y bash jq
    - name: Validate source files
      run: |
        chmod +x build/validate.sh
        ./build/validate.sh

  build:
    runs-on: ubuntu-latest
    needs: validate
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y bash
    - name: Build resource agent
      run: |
        chmod +x build/assemble.sh
        ./build/assemble.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: S3FgwFailOver
        path: S3FgwFailOver

  commit-back:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and commit
      run: |
        chmod +x build/assemble.sh
        ./build/assemble.sh
        git config user.email "action@github.com"
        git config user.name "GitHub Action"
        git add S3FgwFailOver
        git diff --staged --quiet || git commit -m "BOT updating S3FgwFailOver"
        git push
